name: ferdinand_coffee
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  geocoding: ^2.0.1
  share_plus: ^4.0.8
  google_maps_flutter: ^2.1.1
  cached_network_image: ^3.2.0
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  video_player: ^2.4.5
  file_picker: ^4.6.1
  fluttertoast: ^8.0.9
  flutter_stripe: ^2.5.0
  url_launcher: ^6.1.2
  flutter_launcher_icons: "^0.9.2"
  flutter_easyloading: ^3.0.3
  awesome_dialog: ^2.2.1
  image_picker: ^0.8.5
  dio: ^4.0.6
  overlay_support: ^1.2.1
  provider: ^6.0.2

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/images/temp/.
    - assets/icons/.
    - assets/icons/.
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir_Black.otf
          weight: 700
        - asset: assets/fonts/Avenir_Medium.otf
          weight: 400
        - asset: assets/fonts/Avenir_Bold.otf
          weight: 500
